// Thumbnail Mapping - Portfolio to Timeline
// Generated: 2026-02-03T22:17:00.698Z

const THUMBNAIL_MAP = {
  "google-creator-labs-comprehensive": "images/cargo/google-creator-labs-comprehensive.jpeg",
  "reel": "images/cargo/reel.gif",
  "piaget-michael-b-jordan": "images/cargo/piaget-michael-b-jordan.gif",
  "target-lil-yachty-carly-rae-jepsen": "images/cargo/target-lil-yachty-carly-rae-jepsen.gif",
  "complex-networks-reel": "images/cargo/complex-networks-reel.gif",
  "adidas-kylie-jenner": "images/cargo/adidas-kylie-jenner.gif",
  "finish-line-nike": "images/cargo/finish-line-nike.gif",
  "adidas-jd-sports": "images/cargo/adidas-jd-sports.gif",
  "puma-jd-sports": "images/cargo/puma-jd-sports.gif",
  "snapple-elements-nft": "images/cargo/snapple-elements-nft.gif",
  "jhene-aiko-love": "images/cargo/jhene-aiko-love.gif",
  "jhene-aiko-surrender": "images/cargo/jhene-aiko-surrender.gif",
  "jhene-aiko-summer-2020": "images/cargo/jhene-aiko-summer-2020.png",
  "lil-yachty-1-night": "images/cargo/lil-yachty-1-night.gif",
  "og-maco-u-guessed-it": "images/cargo/og-maco-u-guessed-it.gif",
  "tove-lo-jacques": "images/cargo/tove-lo-jacques.gif",
  "tobi-lou-non-perishable": "images/cargo/tobi-lou-non-perishable-mv.gif",
  "madeon-all-my-friends": "images/cargo/madeon-all-my-friends.gif",
  "tobi-lou-lingo-starr": "images/cargo/tobi-lou-lingo-starr.gif",
  "bryson-tiller-inhale": "images/cargo/bryson-tiller-inhale.png",
  "24kgoldn-city-of-angels": "images/cargo/24kgoldn-city-of-angels.gif",
  "tobi-lou-troop": "images/cargo/tobi-lou-troop.gif",
  "cousin-stizz-perfect": "images/cargo/cousin-stizz-perfect.gif",
  "sango-khlorine": "images/cargo/sango-khlorine.gif",
  "lil-yachty-boom": "images/cargo/lil-yachty-boom.png",
  "tobi-lou-hot-tub": "images/cargo/tobi-lou-hot-tub.png",
  "kid-cudi-insano": "images/cargo/kid-cudi-insano.png",
  "tobi-lou-non-perishable-cover": "images/cargo/tobi-lou-non-perishable.jpg",
  "kid-cudi-porsche": "images/cargo/kid-cudi-porsche.png",
  "kid-cudi-at-the-party": "images/cargo/kid-cudi-at-the-party.png",
  "lauryn-hill-rebel": "images/cargo/lauryn-hill-rebel.jpg",
  "hulu-free-machine": "images/cargo/hulu-free-machine.gif",
  "impermanent-digital": "images/cargo/impermanent-digital.gif",
  "disto-fine-art": "images/cargo/disto-fine-art.gif",
  "jd-sports-ar": "images/cargo/jd-sports-afterpay.jpg",
  "sochi-olympics": "images/cargo/sochi-olympics-new.gif",
  "tobi-lou-game-ova": "images/cargo/tobi-lou-game-ova.gif",
  "tunji-ige-war": "images/cargo/tunji-ige-war.gif",
  "tokyos-revenge": "images/cargo/tokyos-revenge.gif",
  "swizz-beats-dmx-rick-ross": "images/cargo/swizz-beats-dmx-rick-ross.gif",
  "bea-miller-feel-something": "images/cargo/bea-miller-feel-something.gif",
  "wiz-khalifa-alright": "images/cargo/wiz-khalifa-alright.gif",
  "shy-glizzy-volcano": "images/cargo/shy-glizzy-volcano.gif",
  "elley-duhe": "images/cargo/elley-duhe.gif",
  "lil-yachty-66": "images/cargo/lil-yachty-66.gif",
  "vic-mensa-metaphysical": "images/cargo/vic-mensa-metaphysical.gif",
  "young-thug-dirty-shoes": "images/cargo/young-thug-dirty-shoes.gif",
  "amine-campfire": "images/cargo/amine-campfire.gif",
  "bhad-bhabie-hacked": "images/cargo/bhad-bhabie-hacked.gif",
  "mook-boy-juvy": "images/cargo/mook-boy-juvy.jpg",
  "prhyme": "images/cargo/prhyme-video.jpg",
  "fifth-harmony": "images/cargo/fifth-harmony.gif",
  "dua-lipa-genesis": "images/cargo/dua-lipa-genesis.gif",
  "dram-ill-nana": "images/cargo/dram-ill-nana.gif",
  "khalid-location": "images/cargo/khalid-location.gif",
  "smokepurpp-bless-yo-trap": "images/cargo/smokepurpp-bless-yo-trap.gif",
  "migos-motorsport": "images/cargo/migos-motorsport.gif",
  "tobi-lou-2hrs": "https://img.youtube.com/vi/2Gaxt3zP8Sg/hqdefault.jpg"
};

// Usage in timeline:
// If project._id matches a key in THUMBNAIL_MAP, use that image
// Otherwise fall back to YouTube thumbnail or placeholder
